server {
    listen 80;
    server_name mydeaLineBot 152.42.184.65;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}
