events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  # Go backend running on Windows (host)
  upstream goapi {
    server host.docker.internal:8080;
  }

  upstream frontEnd {
    server host.docker.internal:8081;
  }

  upstream frontHandler {
    server host.docker.internal:8082;
  }

  server {
    listen 3000;
    server_name localhost;

    # Show default nginx page on /
    root  /usr/share/nginx/html;
    index index.html;

    # Forward /bot/* to Go
    # /bot/callback  ->  http://host.docker.internal:8080/callback
    location /bot/ {
      proxy_pass http://goapi/;   # trailing / strips "/bot/"
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
      try_files $uri $uri/ =404;
    }

    location /_next/ {
      proxy_pass http://frontEnd/_next/;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # dev websocket/hmr
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location = /favicon.ico {
      proxy_pass http://frontEnd/favicon.ico;
      proxy_set_header Host $host;
    }

    location /front/ {
    proxy_pass http://frontEnd/;   # trailing / strips
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /front-api/ {
      proxy_pass http://frontHandler/;   # trailing / strips "/front-api/"
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
