upstream goapi {
    server samdang-bot:8080;
}

upstream frontEnd {
    server samdang-frontend:8081;
}

upstream frontHandler {
    server samdang-front-handler:8082;
}

server {
    listen 443 ssl;
    server_name ${NGINX_SERVER_NAMES};

    ssl_certificate /etc/nginx/ssl/cloudflare/origin.crt;
    ssl_certificate_key /etc/nginx/ssl/cloudflare/origin.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    location /bot/ {
        proxy_pass http://goapi/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /_next/ {
        proxy_pass http://frontEnd/_next/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location = /favicon.ico {
        proxy_pass http://frontEnd/favicon.ico;
        proxy_set_header Host $host;
    }

    location /front/ {
        proxy_pass http://frontEnd/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /front-api/ {
        proxy_pass http://frontHandler/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
