services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./nginx/.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/ssl/cloudflare:/etc/nginx/ssl/cloudflare:ro
    networks:
      - samdang

networks:
  samdang:
    external: true
    name: samdang
